# -*- coding: utf-8 -*-
"""Bayesian Parts (ASYNCH.feb27)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-44PsB59j1jDmGosVM0Uy4C4YUbot-V
"""

# created by: Jheremia B. Villajuan - Friday Feb 27, 2026

# THE PRIOR
import scipy.stats as stat
import numpy as np
import matplotlib.pyplot as plt

mh = np.linspace(1.65, 1.8, num = 50)
test = np.linspace(0, 2)
uniform_dist = stat.uniform.pdf(mh) + 1

uniform_dist = uniform_dist/uniform_dist.sum()
beta_dist = stat.beta.pdf(mh, 2, 5, loc = 1.65, scale = 0.2)
beta_dist = beta_dist/beta_dist.sum()
plt.plot(mh, beta_dist, label = 'Beta Distribution', color = 'violet')
plt.plot(mh, uniform_dist, label = 'Uniform Distribution', color = 'blue')
plt.title("Prior Distribution P(θ) ")
plt.xlabel("Value of \N{GREEK SMALL LETTER MU} in meters")
plt.ylabel("Probability Density")
plt.legend()

# THE LIKELIHOOD

def likelihood_func(datum, mh) :
  likelihood_out = sts.norm.pdf(datum, mh, scale = 0.1)
  return likelihood_out/likelihood_out.sum()

likelihood_out = likelihood_func(1.7, mh)

plt.plot(mh, likelihood_out, color = 'green')
plt.title("Likelihood of \N{GREEK SMALL LETTER MU} Given Observation 1.7m,\nLikelihood P(Data | θ)")
plt.ylabel("Probability Density/Likelihood")
plt.xlabel("Value of \N{GREEK SMALL LETTER MU}")
plt.show()

# THE UNNORMALIZED POSTERIOR

unnormalized_posterior = likelihood_out * uniform_dist
plt.plot(mh, unnormalized_posterior, color = 'brown')
plt.ylabel("Unnormalized Posterior")
plt.xlabel("\N{GREEK SMALL LETTER MU} in meters")
plt.show ()

evidence = np.sum(unnormalized_posterior)

posterior = unnormalized_posterior / evidence

plt.figure()
plt.plot(mh, posterior, color = "green")
plt.title("Posterior Distribution P(θ | Data)")
plt.xlabel("\N{GREEK SMALL LETTER MU} (Mean Height)")
plt.ylabel("Posterior Probability")
plt.show()